name: gs_pyb_comb
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=2.0.1+cu118
  # - torchvision=0.15.2
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - keras-ncp==2.0.5
    - tqdm
    - joblib
    - marshmallow
    - gym
    - pybullet==3.2.5
    - matplotlib==3.5.3
    - scipy
    - ninja
    - tensorflow==2.4.4