name: gaussian_splatting_debug
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=2.0.1
  - torchvision=0.15.2
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn